name: simple plan to destroy resources created via Terraform

on: [workflow_dispatch]


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env: 
      TF_VAR_GITHUB_TOKEN: ${{ secrets.MY_FULL_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: check repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: terraform init
        run: terraform init

      - name: terraform destroy
        run: terraform destroy -auto-approve -var="github_token=${{ secrets.MY_FULL_PAT }}"
        
  
  
