name: control github via terraform

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch Microsoft Entra Groups and Users"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_token: ${{ secrets.MY_FULL_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: check repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan -var="github_token=${{ secrets.MY_FULL_PAT }}"
        

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve -var="github_token=${{ secrets.MY_FULL_PAT }}"
        
  
    
